// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ThebookClientProgram;
impl sails_rs::client::Program for ThebookClientProgram {}
pub trait ThebookClient {
    type Env: sails_rs::client::GearEnv;
    fn orderbook(&self) -> sails_rs::client::Service<orderbook::OrderbookImpl, Self::Env>;
    fn amm(&self) -> sails_rs::client::Service<amm::AmmImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ThebookClient
    for sails_rs::client::Actor<ThebookClientProgram, E>
{
    type Env = E;
    fn orderbook(&self) -> sails_rs::client::Service<orderbook::OrderbookImpl, Self::Env> {
        self.service(stringify!(Orderbook))
    }
    fn amm(&self) -> sails_rs::client::Service<amm::AmmImpl, Self::Env> {
        self.service(stringify!(Amm))
    }
}
pub trait ThebookClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<ThebookClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ThebookClientCtors
    for sails_rs::client::Deployment<ThebookClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<ThebookClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod orderbook {
    use super::*;
    pub trait Orderbook {
        type Env: sails_rs::client::GearEnv;
        fn cancel_order(
            &mut self,
            oid: u64,
        ) -> sails_rs::client::PendingCall<io::CancelOrder, Self::Env>;
        fn challenge(
            &mut self,
            opponent: ActorId,
            amount: u64,
        ) -> sails_rs::client::PendingCall<io::Challenge, Self::Env>;
        fn join(&mut self) -> sails_rs::client::PendingCall<io::Join, Self::Env>;
        fn market_buy(
            &mut self,
            asset: Asset,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::MarketBuy, Self::Env>;
        fn market_sell(
            &mut self,
            asset: Asset,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::MarketSell, Self::Env>;
        fn place_limit(
            &mut self,
            side: Side,
            asset: Asset,
            price: u64,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::PlaceLimit, Self::Env>;
        fn push_oracle_data(
            &mut self,
            oracle: ActorId,
            data: u64,
        ) -> sails_rs::client::PendingCall<io::PushOracleData, Self::Env>;
        fn signal_collab(
            &mut self,
            partner: ActorId,
            _note: String,
        ) -> sails_rs::client::PendingCall<io::SignalCollab, Self::Env>;
        fn start_autopilot(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::StartAutopilot, Self::Env>;
        fn subscribe_oracle(
            &mut self,
            oracle: ActorId,
            label: String,
        ) -> sails_rs::client::PendingCall<io::SubscribeOracle, Self::Env>;
        fn tick(&mut self) -> sails_rs::client::PendingCall<io::Tick, Self::Env>;
        fn get_leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetLeaderboard, Self::Env>;
        fn get_my_orders(&self) -> sails_rs::client::PendingCall<io::GetMyOrders, Self::Env>;
        fn get_orderbook(
            &self,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::GetOrderbook, Self::Env>;
        fn get_portfolio(&self) -> sails_rs::client::PendingCall<io::GetPortfolio, Self::Env>;
        fn get_status(&self) -> sails_rs::client::PendingCall<io::GetStatus, Self::Env>;
        fn get_trades(
            &self,
            asset: Asset,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetTrades, Self::Env>;
    }
    pub struct OrderbookImpl;
    impl<E: sails_rs::client::GearEnv> Orderbook for sails_rs::client::Service<OrderbookImpl, E> {
        type Env = E;
        fn cancel_order(
            &mut self,
            oid: u64,
        ) -> sails_rs::client::PendingCall<io::CancelOrder, Self::Env> {
            self.pending_call((oid,))
        }
        fn challenge(
            &mut self,
            opponent: ActorId,
            amount: u64,
        ) -> sails_rs::client::PendingCall<io::Challenge, Self::Env> {
            self.pending_call((opponent, amount))
        }
        fn join(&mut self) -> sails_rs::client::PendingCall<io::Join, Self::Env> {
            self.pending_call(())
        }
        fn market_buy(
            &mut self,
            asset: Asset,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::MarketBuy, Self::Env> {
            self.pending_call((asset, qty))
        }
        fn market_sell(
            &mut self,
            asset: Asset,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::MarketSell, Self::Env> {
            self.pending_call((asset, qty))
        }
        fn place_limit(
            &mut self,
            side: Side,
            asset: Asset,
            price: u64,
            qty: u64,
        ) -> sails_rs::client::PendingCall<io::PlaceLimit, Self::Env> {
            self.pending_call((side, asset, price, qty))
        }
        fn push_oracle_data(
            &mut self,
            oracle: ActorId,
            data: u64,
        ) -> sails_rs::client::PendingCall<io::PushOracleData, Self::Env> {
            self.pending_call((oracle, data))
        }
        fn signal_collab(
            &mut self,
            partner: ActorId,
            _note: String,
        ) -> sails_rs::client::PendingCall<io::SignalCollab, Self::Env> {
            self.pending_call((partner, _note))
        }
        fn start_autopilot(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::StartAutopilot, Self::Env> {
            self.pending_call(())
        }
        fn subscribe_oracle(
            &mut self,
            oracle: ActorId,
            label: String,
        ) -> sails_rs::client::PendingCall<io::SubscribeOracle, Self::Env> {
            self.pending_call((oracle, label))
        }
        fn tick(&mut self) -> sails_rs::client::PendingCall<io::Tick, Self::Env> {
            self.pending_call(())
        }
        fn get_leaderboard(
            &self,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetLeaderboard, Self::Env> {
            self.pending_call((limit,))
        }
        fn get_my_orders(&self) -> sails_rs::client::PendingCall<io::GetMyOrders, Self::Env> {
            self.pending_call(())
        }
        fn get_orderbook(
            &self,
            asset: Asset,
        ) -> sails_rs::client::PendingCall<io::GetOrderbook, Self::Env> {
            self.pending_call((asset,))
        }
        fn get_portfolio(&self) -> sails_rs::client::PendingCall<io::GetPortfolio, Self::Env> {
            self.pending_call(())
        }
        fn get_status(&self) -> sails_rs::client::PendingCall<io::GetStatus, Self::Env> {
            self.pending_call(())
        }
        fn get_trades(
            &self,
            asset: Asset,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetTrades, Self::Env> {
            self.pending_call((asset, limit))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(CancelOrder (oid: u64) -> Result<(), super::ContractError>);
        sails_rs::io_struct_impl!(Challenge (opponent: ActorId, amount: u64) -> Result<u32, super::ContractError>);
        sails_rs::io_struct_impl!(Join () -> (u64,u64,u64,u64,));
        sails_rs::io_struct_impl!(MarketBuy (asset: super::Asset, qty: u64) -> Result<String, super::ContractError>);
        sails_rs::io_struct_impl!(MarketSell (asset: super::Asset, qty: u64) -> Result<String, super::ContractError>);
        sails_rs::io_struct_impl!(PlaceLimit (side: super::Side, asset: super::Asset, price: u64, qty: u64) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(PushOracleData (oracle: ActorId, data: u64) -> ());
        sails_rs::io_struct_impl!(SignalCollab (partner: ActorId, _note: String) -> ());
        sails_rs::io_struct_impl!(StartAutopilot () -> ());
        sails_rs::io_struct_impl!(SubscribeOracle (oracle: ActorId, label: String) -> ());
        sails_rs::io_struct_impl!(Tick () -> Result<String, super::ContractError>);
        sails_rs::io_struct_impl!(GetLeaderboard (limit: u32) -> Vec<super::LeaderEntry>);
        sails_rs::io_struct_impl!(GetMyOrders () -> Vec<(u64,super::Side,super::Asset,u64,u64,u64,super::OrderStatus,)>);
        sails_rs::io_struct_impl!(GetOrderbook (asset: super::Asset) -> (Vec<(u64,u64,)>,Vec<(u64,u64,)>,));
        sails_rs::io_struct_impl!(GetPortfolio () -> (u64,u64,u64,u64,));
        sails_rs::io_struct_impl!(GetStatus () -> (u32,u64,u32,bool,u32,u32,));
        sails_rs::io_struct_impl!(GetTrades (asset: super::Asset, limit: u32) -> Vec<(u64,u64,u64,ActorId,ActorId,)>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum OrderbookEvents {
            OrderPlaced(OrderPlacedEvent),
            OrderCancelled(OrderCancelledEvent),
            Trade(TradeEvent),
        }
        impl sails_rs::client::Event for OrderbookEvents {
            const EVENT_NAMES: &'static [Route] = &["OrderPlaced", "OrderCancelled", "Trade"];
        }
        impl sails_rs::client::ServiceWithEvents for OrderbookImpl {
            type Event = OrderbookEvents;
        }
    }
}

pub mod amm {
    use super::*;
    pub trait Amm {
        type Env: sails_rs::client::GearEnv;
        fn add_liquidity(
            &mut self,
            pool_id: u64,
            amount_a: u64,
            amount_b: u64,
        ) -> sails_rs::client::PendingCall<io::AddLiquidity, Self::Env>;
        fn create_pool(
            &mut self,
            asset_a: Asset,
            asset_b: Asset,
        ) -> sails_rs::client::PendingCall<io::CreatePool, Self::Env>;
        fn remove_liquidity(
            &mut self,
            pool_id: u64,
            lp_amount: u64,
        ) -> sails_rs::client::PendingCall<io::RemoveLiquidity, Self::Env>;
        fn swap(
            &mut self,
            pool_id: u64,
            asset_in: Asset,
            amount_in: u64,
            min_amount_out: u64,
        ) -> sails_rs::client::PendingCall<io::Swap, Self::Env>;
        fn get_lp_position(
            &self,
            pool_id: u64,
            provider: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetLpPosition, Self::Env>;
        fn get_pool(&self, pool_id: u64) -> sails_rs::client::PendingCall<io::GetPool, Self::Env>;
        fn list_pools(&self) -> sails_rs::client::PendingCall<io::ListPools, Self::Env>;
    }
    pub struct AmmImpl;
    impl<E: sails_rs::client::GearEnv> Amm for sails_rs::client::Service<AmmImpl, E> {
        type Env = E;
        fn add_liquidity(
            &mut self,
            pool_id: u64,
            amount_a: u64,
            amount_b: u64,
        ) -> sails_rs::client::PendingCall<io::AddLiquidity, Self::Env> {
            self.pending_call((pool_id, amount_a, amount_b))
        }
        fn create_pool(
            &mut self,
            asset_a: Asset,
            asset_b: Asset,
        ) -> sails_rs::client::PendingCall<io::CreatePool, Self::Env> {
            self.pending_call((asset_a, asset_b))
        }
        fn remove_liquidity(
            &mut self,
            pool_id: u64,
            lp_amount: u64,
        ) -> sails_rs::client::PendingCall<io::RemoveLiquidity, Self::Env> {
            self.pending_call((pool_id, lp_amount))
        }
        fn swap(
            &mut self,
            pool_id: u64,
            asset_in: Asset,
            amount_in: u64,
            min_amount_out: u64,
        ) -> sails_rs::client::PendingCall<io::Swap, Self::Env> {
            self.pending_call((pool_id, asset_in, amount_in, min_amount_out))
        }
        fn get_lp_position(
            &self,
            pool_id: u64,
            provider: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetLpPosition, Self::Env> {
            self.pending_call((pool_id, provider))
        }
        fn get_pool(&self, pool_id: u64) -> sails_rs::client::PendingCall<io::GetPool, Self::Env> {
            self.pending_call((pool_id,))
        }
        fn list_pools(&self) -> sails_rs::client::PendingCall<io::ListPools, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddLiquidity (pool_id: u64, amount_a: u64, amount_b: u64) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(CreatePool (asset_a: super::Asset, asset_b: super::Asset) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(RemoveLiquidity (pool_id: u64, lp_amount: u64) -> Result<(u64,u64,), super::ContractError>);
        sails_rs::io_struct_impl!(Swap (pool_id: u64, asset_in: super::Asset, amount_in: u64, min_amount_out: u64) -> Result<u64, super::ContractError>);
        sails_rs::io_struct_impl!(GetLpPosition (pool_id: u64, provider: ActorId) -> Option<super::LpPosition>);
        sails_rs::io_struct_impl!(GetPool (pool_id: u64) -> Option<super::Pool>);
        sails_rs::io_struct_impl!(ListPools () -> Vec<super::Pool>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum AmmEvents {
            PoolCreated(PoolCreatedEvent),
            LiquidityAdded(LiquidityAddedEvent),
            LiquidityRemoved(LiquidityRemovedEvent),
            SwapExecuted(SwapExecutedEvent),
        }
        impl sails_rs::client::Event for AmmEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "PoolCreated",
                "LiquidityAdded",
                "LiquidityRemoved",
                "SwapExecuted",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for AmmImpl {
            type Event = AmmEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum ContractError {
    NotAuthorized,
    NotAdmin,
    BadParams,
    JoinFirst,
    InsufficientUsd,
    InsufficientAsset,
    OrderNotFound,
    OrderAlreadyDone,
    NoLiquidity,
    NoBuyers,
    PoolExists,
    PoolNotFound,
    SameAssetPool,
    InsufficientLiquidity,
    SlippageExceeded,
    ZeroAmount,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Asset {
    BTC,
    ETH,
    VARA,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum Side {
    Buy,
    Sell,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LeaderEntry {
    pub id: ActorId,
    pub usd: u64,
    pub net_worth: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum OrderStatus {
    Open,
    Partial,
    Filled,
    Cancelled,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct OrderPlacedEvent {
    pub trader: ActorId,
    pub side: Side,
    pub asset: Asset,
    pub price: u64,
    pub qty: u64,
    pub order_id: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct OrderCancelledEvent {
    pub trader: ActorId,
    pub order_id: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct TradeEvent {
    pub trade_id: u64,
    pub asset: Asset,
    pub price: u64,
    pub qty: u64,
    pub buyer: ActorId,
    pub seller: ActorId,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LpPosition {
    pub pool_id: u64,
    pub provider: ActorId,
    pub amount: u64,
    pub share_a: u64,
    pub share_b: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Pool {
    pub id: u64,
    pub asset_a: Asset,
    pub asset_b: Asset,
    pub reserve_a: u64,
    pub reserve_b: u64,
    pub total_lp: u64,
    pub creator: ActorId,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct PoolCreatedEvent {
    pub pool_id: u64,
    pub asset_a: Asset,
    pub asset_b: Asset,
    pub creator: ActorId,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LiquidityAddedEvent {
    pub pool_id: u64,
    pub provider: ActorId,
    pub amount_a: u64,
    pub amount_b: u64,
    pub lp_minted: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LiquidityRemovedEvent {
    pub pool_id: u64,
    pub provider: ActorId,
    pub amount_a: u64,
    pub amount_b: u64,
    pub lp_burned: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SwapExecutedEvent {
    pub pool_id: u64,
    pub trader: ActorId,
    pub asset_in: Asset,
    pub amount_in: u64,
    pub asset_out: Asset,
    pub amount_out: u64,
    pub fee: u64,
}
